### PR TITLE
added PasswordGenerator class and a unit test for it

### PR DESCRIPTION
**Pull request by st61014**
also included generated passwords in already existing Main code

### CODE REVIEW

**Comment by rodi0878** [comment]
i really hate that three boolean parameters - please make it more explicit what these do and pass them via some configuration object
and please update for new project structure

**Comment by st61014** [comment]
closed by accident apparently

**Comment by st61014** [comment]
Reopening this request to reflect what changes have been made

**Comment by st61014** [comment]
Requested changes have been implemented in commit 9ff2bd7

**Pull request merged**
